spring:
  application:
    name: assessment
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true  #http://localhost:8081/h2-console
    console.path: /h2-console
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false
  sql.init:
    mode: always
    continue-on-error: true

server:
  port: 8081

