INSERT INTO DEPT (ID, NAME, IS_ACTIVE) VALUES (1, 'USA', TRUE );
INSERT INTO DEPT (ID, NAME, IS_ACTIVE) VALUES (2, 'FRANCE', TRUE);
INSERT INTO DEPT (ID, NAME, IS_ACTIVE) VALUES (3, 'BRAZIL', TRUE);
INSERT INTO DEPT (ID, NAME, IS_ACTIVE) VALUES (4, 'ITALY', TRUE);
INSERT INTO DEPT (ID, NAME, IS_ACTIVE) VALUES (5, 'CANADA', TRUE);

commit;